# This Dockerfile is provided if you want to add extra plugins.
# Note that, when you add plugins, you'll need to build your own image and update docker-compose accordingly.
FROM docker.elastic.co/beats/filebeat:6.6.0
#COPY filebeat.yml /usr/share/filebeat/filebeat.yml
#USER root
#RUN chown filebeat /usr/share/filebeat/filebeat.yml
#USER filebeat