# This Dockerfile is provided if you want to add extra plugins.
# Note that, when you add plugins, you'll need to build your own image and update docker-compose accordingly.
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.0

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
