# This Dockerfile is provided if you want to add extra plugins.
# Note that, when you add plugins, you'll need to build your own image and update docker-compose accordingly.
FROM docker.elastic.co/logstash/logstash-oss:6.6.0

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
